### PR TITLE
Fix Problem with opening files in Python3

### PR DESCRIPTION
**Pull request by drunsinn**
Hi,

python3 dosen't have string decoding anymore as every string is supposed to be unicode. 

I tried running the unites and the demos, both work as expected.

### CODE REVIEW

**Comment by apshu** [comment]
Hi drunsinn,

  Thank you for your interest in HersheyFonts.

   About your pull request, I am not understanding the changes very much.

   I would guess the only change relevant to the Head is the check if the read_from_string_lines function got string lines as input, that are decodable.
  Do I see correctly?

Thanks!
   Attila

**Comment by drunsinn** [comment]
Hello Attila,

Thanks for the response and this great library :-)
Yes, your assumption is correct. Only the changes in the lines 372 to 375 are actually necessary.
I didn't realize I left the other stuff in, they are only remnants of my tests to find the best solution. I will update my pull request to "undo" the other non necessary changes!

Regards,
Max

**Comment by drunsinn** [comment]
Hello Attila,
any updates on this PR? Should I change something else?

**Review by apshu — APPROVED** [review]

**Comment by apshu** [comment]
Hi Max,
    Sorry for the delayed response. I was busy with other projects.

    Thanks a lot for your contribution! 

Wish you a great day!

     Attila

**Pull request merged**
